// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADUY4xHpIZ39hAfoYKNBv1nuyYkYIAILc',
    appId: '1:646426749123:web:e6ad3bab41606e4a0c9a76',
    messagingSenderId: '646426749123',
    projectId: 'rove-fcfd4',
    authDomain: 'rove-fcfd4.firebaseapp.com',
    storageBucket: 'rove-fcfd4.appspot.com',
    measurementId: 'G-H9VEG606R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvAd_ZJ7AFeC4bGoWf6ebE55e4YZCtYiY',
    appId: '1:646426749123:android:5b91bed50bc4dc8d0c9a76',
    messagingSenderId: '646426749123',
    projectId: 'rove-fcfd4',
    storageBucket: 'rove-fcfd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdCCsD60L6NAp7s6zG-CVAN2q3bOfpkJo',
    appId: '1:646426749123:ios:35dbc99c49ddadb40c9a76',
    messagingSenderId: '646426749123',
    projectId: 'rove-fcfd4',
    storageBucket: 'rove-fcfd4.appspot.com',
    iosBundleId: 'com.example.rove',
  );
}
